### ISSUE TITLE
Remove spam from CMake script

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-simulation/lib_manager#2]
I get these messages everywhere:

```
CMake Warning at /home/afabisch/Sandbox/bolero/install/share/lib_manager/cmake/lib_manager.cmake:27 (message):
  git repository has local uncommitted changes!
Call Stack (most recent call first):
  CMakeLists.txt:9 (define_module_info)
```

Can we remove them?

(The reason is that I have a git repository in my home directory which has local changes.)

**Comment by malter** [comment]
we can remove that, or add it only for release build

**Comment by AlexanderFabisch** [comment]
I would like to remove that completely. Should I open a pull request or can you do that?

**Comment by malter** [comment]
I can change that tomorrow. I want to keep it optionally because I use it to ensure that I have no local changes when building binaries for benchmarking the learning algorithms. I is important to ensure the the results are reproducible.

**Comment by AlexanderFabisch** [comment]
OK. There are some special cases as well, e.g. if you have git submodules (e.g. in behavior_learning) they are always in the diff-index in practice although they don't have real local changes.

**Comment by malter** [comment]
Message removed.

**Comment by AlexanderFabisch** [comment]
Thanks
