### ISSUE TITLE
Document or get rid of core_libs.txt etc.

### ISSUE THREAD

**Issue by jmetzen** [rock-simulation/lib_manager#3]
Specifying which libs need to be loaded explicitly via core_libs.txt, core_libs-nogui.txt etc. is error-prone and not well documented for new users. This should be either better documented or preferably removed altogether (why is the lib-manager not able to figure out the required libraries for a certain environment in MARS automatically?)
@AlexanderFabisch @bergatt CC

**Comment by AlexanderFabisch** [comment]
> why is the lib-manager not able to figure out the required libraries for a certain environment in MARS automatically?

Each library would have to specify its dependencies to realize this. I believe this should not be too difficult?

**Comment by malter** [comment]
Until now, I was afraid of starting a small application and a whole rock is started automatically in the background, because of dependencies that are not well maintained.
Additionally, many libraries have soft dependencies, they can for example perform with or without gui libraries loaded. These libraries choose their behaviors by asking the lib_manager whether another library is loaded or not. For this principle we need to configure which libraries to load.

**Comment by malter** [comment]
By the way, this issue should move to mars. It is not really lib_manager specific, because a library could already load depending libraries through the lib_manager.

**Comment by jmetzen** [comment]
I would expect that developers of libraries should have a better understanding of dependencies than users and would thus prefer that they maintain an up-to-date list of dependencies in their library rather than expecting the user to do so via a txt-config file.
As for the rest: I am not not to familiar with the inner workings of lib_manager (see me as a user ;-)) and might not to understand how complicate things are below the surface, but what I would expect from an "intelligent" lib-manager is that I specify what I would want to run (which environment, with or without GUI etc.) and it figures out on its own which libraries need to be loaded. Maybe that would require more work on the lib-manager than anyone is able to do at the moment, but then: could we improve the documentation at least? I had no clue today what modules I would have to put in core_libs.txt to get an environment running without GUI and would have been totally lost without Constantin's support.

**Comment by malter** [comment]
Still, this is not part of the lib_manager functionality. Libraries that have hard dependencies can already load them by using the lib_manager, and there are some libraries that do it already. However, somewhere you have to configure whether you want to load the gui or not, whether you want to have a 3d_visualization or not, wether you want to load additional debuging or plotting libraries or not. Most of the libraries are optional dependencies and currently handled by the application via config files (again not by the lib_manager).
In your case it is a problem of MARS or more specific the mars_environment of the internal DFKI learning framework.
MARS on it's own doesn't need this config files.

**Comment by AlexanderFabisch** [comment]
Instead of loading the dependencies directly in the lib_manager, each library could specify its hard dependencies and the lib_manager could print a warning for each missing requirement.

**Comment by malter** [comment]
Just added an optional bool parameter to getLibraryAs. If set, the LibManager tries to load the library if it is not already loaded. With this option, libraries can load their hard dependencies on it's own.

More complex dependency handling will not move into the LibManager to keep the interface as simple as possible.

The concrete issues listed here are solved on the application side, however, if there is still a need for dependency handling in the LibManager this Issue can be reopend. ^-^
